### ISSUE TITLE
Unity 6 Compatability

### ISSUE THREAD

**Issue by Screamycat** [saimarei/URPGlitch#1]
It seems though as for the newer versions of unity, or rather the newest version being unity 6, errors appear that I myself have tried to fix with no avail. I would love a updated version of this repo as I have not found anything greater than this effect!

**Comment by Screamycat** [comment]
Assets\URPGlitch\Runtime\AnalogGlitch\AnalogGlitchRenderPass.cs(56,30): warning CS0672: Member 'AnalogGlitchRenderPass.Execute(ScriptableRenderContext, ref RenderingData)' overrides obsolete member 'ScriptableRenderPass.Execute(ScriptableRenderContext, ref RenderingData)'. Add the Obsolete attribute to 'AnalogGlitchRenderPass.Execute(ScriptableRenderContext, ref RenderingData)'.

Assets\URPGlitch\Runtime\DigitalGlitch\DigitalGlitchRenderPass.cs(71,30): warning CS0672: Member 'DigitalGlitchRenderPass.Configure(CommandBuffer, RenderTextureDescriptor)' overrides obsolete member 'ScriptableRenderPass.Configure(CommandBuffer, RenderTextureDescriptor)'. Add the Obsolete attribute to 'DigitalGlitchRenderPass.Configure(CommandBuffer, RenderTextureDescriptor)'.

Assets\URPGlitch\Runtime\DigitalGlitch\DigitalGlitchRenderPass.cs(86,30): warning CS0672: Member 'DigitalGlitchRenderPass.Execute(ScriptableRenderContext, ref RenderingData)' overrides obsolete member 'ScriptableRenderPass.Execute(ScriptableRenderContext, ref RenderingData)'. Add the Obsolete attribute to 'DigitalGlitchRenderPass.Execute(ScriptableRenderContext, ref RenderingData)'.

Assets\URPGlitch\Runtime\AnalogGlitch\AnalogGlitchRenderPass.cs(27,9): error CS0619: 'RenderTargetHandle' is obsolete: 'Deprecated in favor of RTHandle'

Assets\URPGlitch\Runtime\DigitalGlitch\DigitalGlitchRenderPass.cs(29,9): error CS0619: 'RenderTargetHandle' is obsolete: 'Deprecated in favor of RTHandle'

Assets\URPGlitch\Runtime\DigitalGlitch\DigitalGlitchRenderPass.cs(30,9): error CS0619: 'RenderTargetHandle' is obsolete: 'Deprecated in favor of RTHandle'

Assets\URPGlitch\Runtime\DigitalGlitch\DigitalGlitchRenderPass.cs(31,9): error CS0619: 'RenderTargetHandle' is obsolete: 'Deprecated in favor of RTHandle'

**Comment by saimarei** [comment]
there are some things which get broken in the new versions of unity that I dont know how to fix properly but I was able to make it completely functional albeit with some workarounds, this was for 2023 version of unity so I am not sure if this will work for unity 6. I will try and update the package if the fix works out.

**Comment by saimarei** [comment]
I was able to get it to work but only in compatibility mode, it needs to be re written with render graph system in mind. I will try to do it but I have no experience with it as of now. If it works out I will share a new package later and if it doesnt then I will share you the updated render pass files and you could turn on render graph compatibility and try your hand at it.

**Comment by Screamycat** [comment]
Thanks so much for the good effort and keeping me updated! Good luck, I hope it dose not cause you too much problems ;)

**Comment by saimarei** [comment]
sorry dude, I tried but it seems I need more time to get it to work and I am really busy for the next few days. I have packaged the current solution which works with compatibility mode enabled. I will get back to it when I am free and in the meantime if you want you could just use this or look into urp's render graph samples and implementation and updating it. check out the latest release and tell me if it works for you.

**Comment by Screamycat** [comment]
I can see what i can do, thanks in the meantime.

**Comment by Screamycat** [comment]
As I have tried many things, all my solutions bring yet more problems and hair pulling haha. So I will put this to rest from my side for a while. But if you ever manage to make this package work, do let me know as I still find use for it! 
Sorry for not bringing any luck to the table ;)

**Comment by saimarei** [comment]
Its been months but I have updated the package to work with the render graph and also the compatibility mode. check it out if you still need it and tell me if you face any problems. I am closing this issue.
