### ISSUE TITLE
Can not change glitch values from script

### ISSUE THREAD

**Issue by RedboxSoft** [saimarei/URPGlitch#2]
I need to controll glitch values from script, but by some reason it is not working. Do you have any ideas how to fix this?

`private AnalogGlitchVolume glitch;
    void Start()
    {
        Volume postProcessVolume = GameObject.FindGameObjectWithTag("GlobalVolume").GetComponent<Volume>();
        postProcessVolume.profile.TryGet<AnalogGlitchVolume>(out glitch);

        glitch.colorDrift = new ClampedFloatParameter(0.5f, 0f, 1f);
        glitch.scanLineJitter = new ClampedFloatParameter(0.5f, 0f, 1f);
        glitch.verticalJump = new ClampedFloatParameter(0.5f, 0f, 1f);
    }`

**Comment by saimarei** [comment]
check if you are actually getting the volume. 


this was my old example I gave a few years ago so try out if this code works to test,
```
using UnityEngine;
using UnityEngine.Rendering;
using URPGlitch.Runtime.AnalogGlitch;

public class ExmapleClass : MonoBehaviour
{
    [SerializeField] Volume volume;

    AnalogGlitchVolume analogGlitchVolume;

    private void Start()
    {
        volume.profile.TryGet<AnalogGlitchVolume>(out analogGlitchVolume);
    }

    public void ChangeEffect()
    {
        analogGlitchVolume.scanLineJitter.value = 0.25f;
        analogGlitchVolume.verticalJump.value = 0.25;
        analogGlitchVolume.horizontalShake.value = 0.25f;
        analogGlitchVolume.colorDrift.value = 0.25f;
    }
}
```

**Comment by saimarei** [comment]
I am gonna be porting the package to work with the rendergraph stuff. unity 6 urp is a pain right now tbh so probably the last update until they change up things a lot.

**Comment by RedboxSoft** [comment]
Thank you for the quick reply! 
This works as expected: analogGlitchVolume.scanLineJitter.value = 0.25f;
